import { StyleSheet, StatusBar } from "react-native";

export const globalStyles = StyleSheet.create({
  titleText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    padding: 20,
    marginLeft: 25,
    marginRight: 25,
  },
  headerText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    padding: 20,
    marginLeft: 25,
    marginRight: 25,
    textAlign: "center",
  },
  groupHeaderText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    padding: 10,
    marginHorizontal: 25,
    textAlign: "center",
  },
  header: {
    paddingTop: 10,
    width: "90%",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  defaultText: {
    fontSize: 18,
    fontWeight: "normal",
    color: "#333",
    padding: 20,
    marginLeft: 25,
    marginRight: 25,
    textAlign: "center",
  },
  paragraph: {
    marginVertical: 8,
    lineHeight: 20,
  },
  container: {
    flex: 1,
    backgroundColor: "#fdfdfd",
    alignItems: "center",
    justifyContent: "center",
  },
  container2: {
    flex: 1,
    backgroundColor: "#fdfdfd",
    alignItems: "center",
    marginTop: StatusBar.currentHeight || 100,
    marginBottom: 150,
  },
  innerContainer: {
    flex: 1,
    marginTop: StatusBar.currentHeight || 15,
    marginBottom: 10,
    width: "100%",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    padding: 10,
    fontSize: 18,
    borderRadius: 6,
    minWidth: 240,
    alignItems: "stretch",
  },
  separator: {
    marginVertical: 8,
    borderBottomColor: "#737373",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  fixToText: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  backButton: {
    alignSelf: "flex-beginning",
    marginLeft: 15,
    position: "absolute",
    top: 70,
  },
  topRightButton: {
    alignSelf: "flex-end",
    position: "absolute",
    paddingRight: 10,
    top: 57,
  },
  outlineButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 30,
    elevation: 3,
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#34b7f1",
    borderRadius: 6,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  bottomView: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 40,
  },
  topView: {
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: -20,
  },
  item: {
    backgroundColor: "transparent",
    padding: 15,
    marginVertical: 10,
    marginHorizontal: 16,
  },
  chatContainer: {
    flex: 1,
    marginTop: StatusBar.currentHeight || 0 + 30,
    marginBottom: 200,
    alignSelf: "flex-beginning",
    marginLeft: 25,
  },
  button: {
    alignItems: "center",
    backgroundColor: "#DDDDDD",
    padding: 10,
    color: "#333",
  },
  primaryButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 6,
    elevation: 3,
    backgroundColor: "#1aa7ec",
  },
  primaryButtonText: {
    color: "#fdfdfd",
    fontSize: 18,
  },
  secondaryButtonText: {
    color: "#228ee7",
    fontSize: 18,
  },
  secondaryButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: "transparent",
  },
  buttonContainer: {
    width: "90%",
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 20,
  },
  smallButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 6,
  },
  smallButtonText: {
    color: "#228ee7",
    fontSize: 14,
  },
});
